spring:
  application:
    name: CareVision
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  use-fqn: true

openapi:
  secretkey: ${OPENAPI_SECRET_KEY}

jwt:
  refresh-expiration-time: ${REFRESH_EXPIRATION_TIME}
  access-expiration-time: ${ACCESS_EXPIRATION_TIME}
  secret: ${JWT_SECRET_KEY}

camera:
  streaming:
    url: ${CAMERA_STREAMING_URL}